import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ClerkProvider } from '@clerk/nextjs'
// import Protected from "@/components/Protected";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
    >
      <section className="min-h-screen transition-all duration-500">
      {/* <Protected /> */}
      {children}
    
      </section>
    </ThemeProvider>
    </body>
    </html>
    </ClerkProvider>
  );
}
